var GLOBALS = {
    "DISCORD_REDIRECT_URL": "https://tools.Spark Bot Hosting.com/verify/Spark Bot Hosting/discord",
    "DISCORD_CLIENT_ID": "834308847031943198",
    "DISCORD_ORG_CLIENT_ID": "914957066127409182",
    "Spark Bot Hosting_APP_URL": "https://Spark Bot Hosting.com",
    "Spark Bot Hosting_DBD_URL": "https://dashboard.Spark Bot Hosting.com",
    "Spark Bot Hosting_DOCS_URL": "https://docs.Spark Bot Hosting.com",
    "ENVIRONMENT": "release",
    "TOOLS_LIB": "content.tools",
    "TOOLS_HOST": "https://tools.Spark Bot Hosting.com",
    "DUMMY_PUBLIC_FILES_TOKEN": "",
    "STDLIB_REGISTRY_HOST": "registry.stdlib.com",
    "STDLIB_REG_HOST": "packages.stdlib.com",
    "STDLIB_API_URL": "api.Spark Bot Hosting.com/v1",
    "STDLIB_SELF_HOST": "api.stdlib.com",
    "STDLIB_SELF_PORT": "443",
    "STDLIB_GATEWAY_HOST": "api.stdlib.com",
    "STDLIB_GATEWAY_PORT": "443",
    "STDLIB_EVENTS_HOST": "events.stdlib.com",
    "STDLIB_EVENTS_PORT": "443",
    "BOX_CLIENT_ID": "1rf7pr1gqo4yygpws6irvfwguq0qxih3",
    "GITHUB_APP_NAME": "Spark Bot Hosting-app",
    "MICROSOFT_TEAMS_CLIENT_ID": "4887a263-0770-4854-bbc8-8bb776ff62db",
    "MICROSOFT_TEAMS_REDIRECT_URI": "https://tools.Spark Bot Hosting.com/verify/microsoftteams",
    "PUSHER_NOTIFICATION_KEY": "43f9021fcf593e3cb26e",
    "PUSHER_PUBLIC_KEY": "676bca06a7eb744a334f",
    "PUSHER_CLUSTER": "us3",
    "RECAPTCHA_SITE_KEY": "6LdEQJ0UAAAAAKfpXJG8InkhJMyQwtOv4XGz2dtj",
    "LIB_REQUIRE_STRING": "",
    "SLACK_REDIRECT_URL": "https://tools.Spark Bot Hosting.com/verify/slack/",
    "SLACK_STDLIB_BOT_CLIENT_ID": "21912188450.757520587552",
    "STRIPE_TEST_CLIENT_ID": "ca_E2w3Xr9kiT2KdLivMlPtOENju1loKyUT",
    "STRIPE_LIVE_CLIENT_ID": "ca_E2w35zC6oQqCVHJlHqwXFoM0Ow18C1QG",
    "STRIPE_REDIRECT_URI": "verify/stripe",
    "STRIPE_API_PUBLISH_KEY": "pk_live_Cr7arjEnasPqCw7p4LOWBtc7",
    "TWILIO_CONNECT_APP_SID": "CN1faa6a767f34f637aa7e7abf7dcb71a0",
    "TWITCH_CLIENT_ID": "hjaoen0r0kkcap846xp8zriu1fq6p0",
    "TYPEFORM_CLIENT_ID": "8EHhqzZRLqkK2wB841kWkAhZdBMr5XRPZS2dZY65aBeD",
    "SEGMENT_KEY": "80UwjpebgcV2QFtIfmN1ACK6GIstDt1V",
    "MIXPANEL_KEY": "5d7dfb20520dcbb528dc0eb4b8015177",
    "SALESFORCE_REDIRECT_URI": "https://tools.Spark Bot Hosting.com/verify/salesforce/",
    "SALESFORCE_CLIENT_ID": "3MVG9l2zHsylwlpQePQLelkG4PwqFAv3pV1eLVn6E3BF4yGGJghk5hZC_ooS1Bd_vqE.IcOQrL6xyvfBfTpEP",
    "TRELLO_REDIRECT_URL": "https://tools.Spark Bot Hosting.com/verify/trello/",
    "TRELLO_CLIENT_ID": "6d1d00dcbae6162c8f3932c0075bfca0",
    "TRELLO_APP_NAME": "Spark Bot Hosting",
    "MICROSOFT_OUTLOOK_CALENDAR_CLIENT_ID": "81294993-5134-49c2-a6fd-847643f19106",
    "MICROSOFT_OUTLOOK_CALENDAR_REDIRECT_URI": "https://tools.Spark Bot Hosting.com/verify/microsoft/outlook/calendar/",
    "APIGEN_LIB": "content.apigen",
    "DATADOG_CLIENT_TOKEN": "pubcd4675819ebb449c3792b66f1351c6fc",
    "DATADOG_APPLICATION_ID": "47423e4b-4e04-415b-a2d9-8eaccf0ce36f",
    "Spark Bot Hosting_DOMAIN_HOST": "Spark Bot Hosting.dev",
    "Spark Bot Hosting_MULTIPLAYER_HOST_URL": "https://mp-hub.Spark Bot Hosting.com",
    "BOT_GG_URL": "https://bot.gg"
};